language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_99d53deba8df_key -iv $encrypted_99d53deba8df_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
