language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c12fb402ca61_key -iv $encrypted_c12fb402ca61_iv
  -in src/main/resourdces/application.properties.enc -out src/main/resources/application.properties -d
